export const HW3Events = {
    LEVEL_START: "LEVEL_START",
    LEVEL_END: "LEVEL_END",
    PLAYER_ENTERED_LEVEL_END: "PLAYER_ENTERED_LEVEL_END",
    PROGRESS_BAR: "PROGRESS_BAR",
    HEALTH_CHANGE: "HEALTH_CHANGE",
    COLLISION_DESTRUCTABLE: "COLLISION_DESTRUCTABLE",
    MONKEY_DEAD: "MONKEY_DEAD",
    LASER_MONKEY_COLLISION: "LASER_MONKEY_COLLISION",
    PLAYER_MONKEY_COLLISION: "PLAYER_MONKEY_COLLISION",

    PLAYER_DEAD: "PLAYER_DEAD",

    UPSIDE_DOWN: "UPSIDE_DOWN",

    MOVE_UP: "MOVE_UP",

    MOVE_DOWN: "MOVE_DOWN",

    ON_ROPE: "ON_ROPE",

    FALL_MAP: "FALL_MAP"
    
} as const;
