//Robo_Rush events
export const Robo_RushEvents = {
    LEVEL_START: "LEVEL_START",
	LEVEL_END: "LEVEL_END",
	HEALTH_CHANGE: "HEALTH_CHANGE",
	PLAYER_DEAD: "PLAYER_DEAD",
	LASER_ATTACK: "LASER_ATTACK",
	PLAYER_OBSTACLE_COLLISION: "PLAYER_OBSTACLE_COLLISION",
    WEAPON_CHARGE_CHANGE: "WEAPON_CHARGE_CHANGE",
    PROGRESS_CHANGE: "PROGRESS_CHANGE",
    DEAD: "DEAD",
    W_PRESSED: "W_PRESSED",
    ESC: "ESC"
} as const;